-- MySQL Script generated by MySQL Workbench
-- Sun Jun 26 20:07:50 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hakdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hakdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hakdb` DEFAULT CHARACTER SET utf8 ;
USE `hakdb` ;

-- -----------------------------------------------------
-- Table `hakdb`.`__efmigrationshistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hakdb`.`__efmigrationshistory` (
  `MigrationId` VARCHAR(95) NOT NULL,
  `ProductVersion` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`MigrationId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `hakdb`.`aspnetroles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hakdb`.`aspnetroles` (
  `Id` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `Name` VARCHAR(256) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `NormalizedName` VARCHAR(256) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `ConcurrencyStamp` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `RoleNameIndex` (`NormalizedName` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `hakdb`.`aspnetroleclaims`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hakdb`.`aspnetroleclaims` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `RoleId` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `ClaimType` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `ClaimValue` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_AspNetRoleClaims_RoleId` (`RoleId` ASC) VISIBLE,
  CONSTRAINT `FK_AspNetRoleClaims_AspNetRoles_RoleId`
    FOREIGN KEY (`RoleId`)
    REFERENCES `hakdb`.`aspnetroles` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `hakdb`.`aspnetusers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hakdb`.`aspnetusers` (
  `Id` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `UserName` VARCHAR(256) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `NormalizedUserName` VARCHAR(256) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Email` VARCHAR(256) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `NormalizedEmail` VARCHAR(256) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `EmailConfirmed` TINYINT(1) NOT NULL,
  `PasswordHash` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `SecurityStamp` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `ConcurrencyStamp` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `PhoneNumber` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `PhoneNumberConfirmed` TINYINT(1) NOT NULL,
  `TwoFactorEnabled` TINYINT(1) NOT NULL,
  `LockoutEnd` DATETIME(6) NULL DEFAULT NULL,
  `LockoutEnabled` TINYINT(1) NOT NULL,
  `AccessFailedCount` INT NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `UserNameIndex` (`NormalizedUserName` ASC) VISIBLE,
  INDEX `EmailIndex` (`NormalizedEmail` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `hakdb`.`aspnetuserclaims`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hakdb`.`aspnetuserclaims` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `UserId` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `ClaimType` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `ClaimValue` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_AspNetUserClaims_UserId` (`UserId` ASC) VISIBLE,
  CONSTRAINT `FK_AspNetUserClaims_AspNetUsers_UserId`
    FOREIGN KEY (`UserId`)
    REFERENCES `hakdb`.`aspnetusers` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `hakdb`.`aspnetuserlogins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hakdb`.`aspnetuserlogins` (
  `LoginProvider` VARCHAR(128) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `ProviderKey` VARCHAR(128) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `ProviderDisplayName` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `UserId` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  PRIMARY KEY (`LoginProvider`, `ProviderKey`),
  INDEX `IX_AspNetUserLogins_UserId` (`UserId` ASC) VISIBLE,
  CONSTRAINT `FK_AspNetUserLogins_AspNetUsers_UserId`
    FOREIGN KEY (`UserId`)
    REFERENCES `hakdb`.`aspnetusers` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `hakdb`.`aspnetuserroles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hakdb`.`aspnetuserroles` (
  `UserId` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `RoleId` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  PRIMARY KEY (`UserId`, `RoleId`),
  INDEX `IX_AspNetUserRoles_RoleId` (`RoleId` ASC) VISIBLE,
  CONSTRAINT `FK_AspNetUserRoles_AspNetRoles_RoleId`
    FOREIGN KEY (`RoleId`)
    REFERENCES `hakdb`.`aspnetroles` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_AspNetUserRoles_AspNetUsers_UserId`
    FOREIGN KEY (`UserId`)
    REFERENCES `hakdb`.`aspnetusers` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `hakdb`.`aspnetusertokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hakdb`.`aspnetusertokens` (
  `UserId` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `LoginProvider` VARCHAR(128) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `Name` VARCHAR(128) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `Value` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`UserId`, `LoginProvider`, `Name`),
  CONSTRAINT `FK_AspNetUserTokens_AspNetUsers_UserId`
    FOREIGN KEY (`UserId`)
    REFERENCES `hakdb`.`aspnetusers` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `hakdb`.`authorization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hakdb`.`authorization` (
  `idauthorization` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NULL DEFAULT NULL,
  `pasword` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idauthorization`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `hakdb`.`ndustrial injuries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hakdb`.`ndustrial injuries` (
  `idndustrial injuries` INT NOT NULL AUTO_INCREMENT,
  `The number deaths` VARCHAR(45) NULL DEFAULT NULL,
  `Number of people seriously injured` VARCHAR(45) NULL DEFAULT NULL,
  `Group accidents` VARCHAR(45) NULL DEFAULT NULL,
  `Number of people who received minor injuries` VARCHAR(45) NULL DEFAULT NULL,
  `The number of people who received microtrauma` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idndustrial injuries`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `hakdb`.`pasport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hakdb`.`pasport` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NULL DEFAULT NULL,
  `phone number` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(80) NULL DEFAULT NULL,
  `place` VARCHAR(45) NULL DEFAULT NULL,
  `NameOPF` VARCHAR(80) NULL DEFAULT NULL,
  `fullNameOrg` VARCHAR(45) NULL DEFAULT NULL,
  `ShortNameOrg` VARCHAR(45) NULL DEFAULT NULL,
  `addressLegal` VARCHAR(80) NULL DEFAULT NULL,
  `Full name` VARCHAR(80) NULL DEFAULT NULL,
  `inn` VARCHAR(45) NULL DEFAULT NULL,
  `oktmo` VARCHAR(45) NULL DEFAULT NULL,
  `main activity of OKVED` VARCHAR(45) NULL DEFAULT NULL,
  `phone number 2` VARCHAR(45) NULL DEFAULT NULL,
  `email official` VARCHAR(45) NULL DEFAULT NULL,
  `Full name safety specialist` VARCHAR(45) NULL DEFAULT NULL,
  `phone 3` VARCHAR(45) NULL DEFAULT NULL,
  `email3` VARCHAR(45) NULL DEFAULT NULL,
  `gold type` VARCHAR(45) NULL DEFAULT NULL,
  `idn` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `hakdb`.`sout`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hakdb`.`sout` (
  `idSOUT` INT NOT NULL AUTO_INCREMENT,
  `special assessment` VARCHAR(45) NULL DEFAULT NULL,
  `Date of the SAUT report and the number` VARCHAR(45) NULL DEFAULT NULL,
  `Total jobs in organization` INT NULL DEFAULT NULL,
  `number of workplaces Saut` VARCHAR(45) NULL DEFAULT NULL,
  `%  jobs covered SAUT` VARCHAR(45) NULL DEFAULT NULL,
  `Class 1` VARCHAR(45) NULL DEFAULT NULL,
  `Class 2` VARCHAR(45) NULL DEFAULT NULL,
  `Class 3.1` VARCHAR(45) NULL DEFAULT NULL,
  `Class 3.2` VARCHAR(45) NULL DEFAULT NULL,
  `Class 3.3` VARCHAR(45) NULL DEFAULT NULL,
  `Class 3.4` VARCHAR(45) NULL DEFAULT NULL,
  `Class 4` VARCHAR(45) NULL DEFAULT NULL,
  `harmful anddangerous` FLOAT NULL DEFAULT NULL,
  `SOUTcol` VARCHAR(45) NULL DEFAULT NULL,
  `risks in  field  protection` VARCHAR(45) NULL DEFAULT NULL,
  `Date of the last professional risk assessment` VARCHAR(45) NULL DEFAULT NULL,
  `number of employees receiving workwear for free` INT NULL DEFAULT NULL,
  `Average % of employee security` VARCHAR(45) NULL DEFAULT NULL,
  `The number of employees receiving free flushing and` VARCHAR(45) NULL DEFAULT NULL,
  `Average % of providing employees` VARCHAR(45) NULL DEFAULT NULL,
  `Number of employees for medical` INT NULL DEFAULT NULL,
  `% of employees who have passed` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idSOUT`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
